apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscale
  namespace: test-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
  minReplicas: 1
  maxReplicas: 25
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 10
          periodSeconds: 1
    scaleDown:
      policies:
        - type: Pods
          value: 10
          periodSeconds: 10