apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-keda-scheduled
  namespace: test-namespace
spec:
  scaleTargetRef:
    name: test-deployment
  triggers:
    - type: cron
      metadata:
        timezone: Europe/London
        start: "*/5 * * * *"
        end: "*/10 * * * *"
        desiredReplicas: "50"